[tox]
envlist = py27, py34, py35, py36, pypy, pypy3

[testenv]
deps=pytest
setenv =
  PYTHONPATH = {toxinidir}:{toxinidir}/
commands = py.test tests.py

[tool:pytest]
addopts = --doctest-glob='docs/*.rst'
testpaths = tests.py README.rst


[coverage:run]
source = interval

[coverage:report]
exclude_lines =
	# Have to re-enable the standard pragma
	pragma: no cover

	# Don't complain if tests don't hit defensive assertion code:
	raise NotImplementedError

[coverage:html]
directory = .coverage_html
